### PR TITLE
Fix for #2345: filter out opposed reviewers

### LINKED ISSUE #2354: Empty opposed Reviewer fields preventing users from submitting
A user is able to progress past the Details page with empty opposed Reviewer fields but clicking ‘submit’ throws an error in the console. All the user sees is the submit button not working.

The opposed Reviewer fields should not throw an error if both ‘Name’ and ‘Email’ are empty... only if one or the other is missing, and this validation error should be displayed to the user when clicking ‘Next’ on the Details page.

It seems the error is most commonly occurring when a user fills out the fields for one opposed Reviewer (generating the second row) but then doesn’t add a second.

### PR DESCRIPTION
**Pull request by erezmus**
#### Background

Fixes bug when empty opposed reviewer name and email data are empty string are erroneously rejected by joi validation. The fix is to filter out any empty entries as was done currently for suggested reviewers

#### Any relevant tickets

Contributes to #2354 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

- [x] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

### CODE REVIEW

File: packages/component-model-manuscript/entities/manuscript/index.js [hunk 1]
```diff
@@ -319,10 +319,18 @@ class Manuscript extends BaseModel {
   // would mean applying the input to the manuscript first
   static removeOptionalBlankReviewers(input) {
     const itemIsBlank = item => item.name + item.email === ''
-    const filteredReviewers = input.suggestedReviewers.filter(
+    const filteredSuggestedReviewers = input.suggestedReviewers.filter(
```
Comment (will-byrne) [inline packages/component-model-manuscript/entities/manuscript/index.js:322]: Would it not make more sense to make sure that blank or null entries are not sent from the client rather than removing them on the server?

Comment (erezmus) [reply packages/component-model-manuscript/entities/manuscript/index.js:322]: Ideally we should do both. Given this is impacting users on a seemingly daily basis, it makes sense to do it on the server side first. Happy to do the client side in separate PR.

Comment (diversemix) [reply packages/component-model-manuscript/entities/manuscript/index.js:322]: Agreed

Comment (will-byrne) [reply packages/component-model-manuscript/entities/manuscript/index.js:322]: ok ill mark this as resolved then

**Review by will-byrne — APPROVED** [review]

**Comment by diversemix** [comment]
@erezmus you ok if I take a look at this later and merge it for tonight's deploy?

**Review by diversemix — APPROVED** [review]
