### PR TITLE
1521 error catch

### LINKED ISSUE #1521: Clear the interval set to send upload progress when a process fails on manuscript upload
## Subtasks

As part of #1492 the `upload` function on the `manuscript` controller was broken down into smaller helper functions for each stage of the upload process. One of the reasons for doing this is there is currently a bug in the code that causes the app to continue sending the client 99% progress messages when one of the processes fails but the interval being used to send progress messages is not cleared.

The refactoring should have made it easier to wrap tasks that can throw an Error in a `try..catch` and ensure the interval is cleared when that error occurs. 

## Assumptions and notes

- The most likely culprit for the 99% bug is at the scienceBeam extraction stage as this is wrapped in a try catch already but doesn't clear the interval. 

- ~~Only those functions that throw an error or end the request in some way need to be wrapped~~

- The simplest solution would be to wrap the entire process after calling `startFileProgress`  in a try catch that then call the following when an error is thrown.

```
    } catch (error) {
      endFileProgress(progress)
      pubsub.publish(`${ON_UPLOAD_PROGRESS}.${manuscriptId}`, {
        manuscriptUploadProgress: 100,
      })
      throw error
    }
```

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

 Currently there is a bug that causes the progress of a manuscript upload to get stuck at 99% if an error is thrown due to the setInterval continuing to broadcast progress messages to the client.

This PR wraps the entire `uploadManuscriptFile` process in a `try catch`, clearing the interval and sending a 100% message to the client so that it knows the process has ended (albeit in an error state). The `uploadManuscriptFile` function originally had this clearing functionality at its scienceBeam extraction stage. This has been removed so that `uploadManuscriptFile` no longer has knowledge of the progress tracking task and this is all taken care of in the controller.

#### Any relevant tickets

Closes #1521

### CODE REVIEW

**Review by hem-brahmbhatt — COMMENTED** [review]
Let's add a unit test for this.

**Review by diversemix — APPROVED** [review]

File: server/xpub-controller/helpers/files.js [hunk 1]
```diff
@@ -58,6 +58,26 @@ class FilesHelper {
...
 
+  static startFileProgress(
+    pubsub,
+    ON_UPLOAD_PROGRESS,
+    startedTime,
+    predictedTime,
+    manuscriptId,
+    interval,
+  ) {
+    return setInterval(
```
Comment (Cooryd) [inline server/xpub-controller/helpers/files.js:69]: Added this function to let me mock the calling of `setInterval` in the  maniuscript upload controller unit test without using jest.useFakeTimers as this was throwing errors. see #1553 for a little more context.

**Review by hem-brahmbhatt — APPROVED** [review]
I'm not sure how to reproduce the bug so I haven't been able to test if it's fixed or not. Upload progress still works in the review environment
