### PR TITLE
Fix missing braces in setting originalEmails

### LINKED ISSUE #1289: Spotting bug which will result in multiple emails being sent
Fix the bug...

In `server/xpub-controller/manuscript.js` the value of `originalEmails` is not being set correctly.

### PR DESCRIPTION
**Pull request by diversemix**
#### Background

Stop multiple emails being sent.

#### Any relevant tickets

Closes #1289 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

see #1290

### CODE REVIEW

**Review by jyenes — APPROVED** [review]
pretty straight forward

File: server/xpub-controller/manuscript.js [hunk 1]
```diff
@@ -18,9 +18,12 @@ class Manuscript {
       )
     }
 
-    const originalEmails = manuscript.getAuthor()
+    const originalEmails = (manuscript.getAuthor()
       ? manuscript.getAuthor()
-      : [].map(author => author.alias.email).join(',')
+      : []
+    )
```
Comment (hem-brahmbhatt) [inline server/xpub-controller/manuscript.js:24]:
```suggestion
  const originalEmails =  manuscript.getAuthor() || []
```

Comment (diversemix) [reply server/xpub-controller/manuscript.js:24]: Sorry that was prettify that refactored all that :/
