### PR TITLE
fix bug not displaying manuscript title

### LINKED ISSUE #1708: Manuscript title missed on the send confirmation email.
@diversemix detected the bug:

> I just received a confirmation email for my submission to eLife, however, in the email the title was missing between two ditto symbols, and so I wondered if the submission has been completed correctly. (In the submission system the title appears correctly: "Shared neural underpinnings of multisensory integration and trial-by-trial perceptual recalibration")

looking at the PR: https://github.com/elifesciences/elife-xpub/pull/1674

we have introduced new variable to include the manuscript title:
https://github.com/elifesciences/elife-xpub/blob/8ffd6de8a0469467d064a5032052f522ab4c2a4c/templates/final-submission-email-html.pug#L3

we need to compile the template and send this variable

### PR DESCRIPTION
**Pull request by jyenes**
the manuscript title was not passed over the template, so was not displayed.

closes: #1708

### CODE REVIEW

File: server/xpub-server/entities/manuscript/resolvers/submitManuscript.js [hunk 1]
```diff
@@ -30,7 +30,10 @@ async function submitManuscript(_, { data }, { user, ip }) {
   manuscript.applyInput(manuscriptInput)
 
   const notify = new Notification(config)
-  await notify.sendFinalSubmissionEmail(manuscript.getAuthor())
+  await notify.sendFinalSubmissionEmail(
+    manuscript.getAuthor(),
+    manuscript.meta.title,
+  )
```
Comment (hem-brahmbhatt) [inline server/xpub-server/entities/manuscript/resolvers/submitManuscript.js]: Can we update the test to assert against the email contents?

We can use `.toMatchSnapshot()`

File: server/xpub-server/entities/manuscript/resolvers/submitManuscript.js [hunk 2]
```diff
@@ -30,7 +30,10 @@ async function submitManuscript(_, { data }, { user, ip }) {
   manuscript.applyInput(manuscriptInput)
 
   const notify = new Notification(config)
-  await notify.sendFinalSubmissionEmail(manuscript.getAuthor())
+  await notify.sendFinalSubmissionEmail(
+    manuscript.getAuthor(),
```
Comment (diversemix) [inline server/xpub-server/entities/manuscript/resolvers/submitManuscript.js]: Why not pass in just the `manuscript` object

**Review by diversemix — APPROVED** [review]

**Review by Cooryd — APPROVED** [review]
