### PR TITLE
fix the tests to run with the feature flag

### LINKED ISSUE #2315: Update browser tests for survey page
## Subtasks

- [ ] A description of a subtask
- [ ] A description

## Assumptions and notes
- We could use this technology
- More notes or suggestions

### PR DESCRIPTION
**Pull request by will-byrne**
#### Background

Add page components for survey page and fix existing tests to run with the field enabled.

#### Any relevant tickets

Closes #2315

### CODE REVIEW

**Review by petereast — APPROVED** [review]
Nice

File: packages/component-submission/client/pages/SurveyPage.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ const SurveyPage = ({ submitSurveyResponse, match, history }) => {
       </Paragraph.Writing>
       <Box mb={3}>
         <TextField
+          data-test-id="survey-question-1"
```
Comment (Cooryd) [inline packages/component-submission/client/pages/SurveyPage.js:37]: Just added these in for use in unit tests, will update our PR to match these

**Review by Cooryd — APPROVED** [review]
