### PR TITLE
2171 - wizard step titles

### LINKED ISSUE #2171: Reinstate correct titles on wizard steps
The title for each page of the submission wizard is currently being populated by `STEP_NAMES` (same as the progress indicator) but this is incorrect. The titles of each page should be as follows:

“Author” should be “Your details”

“Files” should be “Your cover letter”

“Details” should be “Help us get your work seen by the right people”

“Editors” should be “Who should review your work”?”

And “Disclosure” should be “Disclosure of data to Editors

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

We were using the same string values for the progress bar labels as wizard step titles, this needed changing to make the titles more descriptive. This adds a new constant value of `STEP_TITLES` which hold the title strings and adds unit tests for checking the correct titles are present on each step.

#### Any relevant tickets

closes #2171 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [x] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

#### UI Changes

- [ ] Has been reviewed against Designs
- [ ] Necessary updates to styleguide

### CODE REVIEW

**Review by will-byrne — APPROVED** [review]

File: packages/component-submission/client/pages/FilesStepPage.js [hunk 1]
```diff
@@ -142,7 +142,6 @@ export class FilesStepPageComponent extends React.Component {
     return (
       <React.Fragment>
         <Box mb={3} width={1}>
-          <FormH2>Your cover letter</FormH2>
```
Comment (erezmus) [inline packages/component-submission/client/pages/FilesStepPage.js:145]: Why is this removed?

File: packages/component-submission/client/pages/SubmissionWizard.js [hunk 2]
```diff
@@ -35,7 +35,7 @@ import {
   getErrorStepsFromErrors,
   convertArrayToReadableList,
 } from '../utils'
-import { STEP_NAMES } from '../utils/constants'
+import { STEP_NAMES, STEP_TITLES } from '../utils/constants'
```
Comment (diversemix) [inline packages/component-submission/client/pages/SubmissionWizard.js:38]: Did you consider changing to something like `STEP_INFO` so we can add any future information to this structure. Seems like adding an additional structures each time might become messy?

**Review by diversemix — APPROVED** [review]

File: packages/component-submission/client/pages/SubmissionWizard.js (hunk 2 above)
Comment (Cooryd) [reply packages/component-submission/client/pages/SubmissionWizard.js:38]: I did think about having just a STEP_CONF value that held everything. This would touch lots of other values though so maybe better too refactor in another issue?

**Comment by hdrury1** [comment]
@Cooryd Should be "Who should review your work?" (notice the question mark)

and

"Disclosure of data to editors" (notice small case 'e' for editors)

File: packages/component-submission/client/pages/SubmissionWizard.js (hunk 2 above)
Comment (diversemix) [reply packages/component-submission/client/pages/SubmissionWizard.js:38]: yup -raise it as an improvement :)

File: packages/component-submission/client/pages/FilesStepPage.js (hunk 1 above)
Comment (Cooryd) [reply packages/component-submission/client/pages/FilesStepPage.js:145]: It's duplicated with the Sub mission level titles. This is the only page with two sets of titles, 'Cover letter' and 'Files'

**Review by erezmus — APPROVED** [review]

File: packages/component-submission/client/pages/SubmissionWizard.js (hunk 2 above)
Comment (Cooryd) [reply packages/component-submission/client/pages/SubmissionWizard.js:38]: #2180 raised as an improvement

**Review by hdrury1 — APPROVED** [review]
