### PR TITLE
1362 - File upload statuses displaying correctly after refresh

### LINKED ISSUE #1362: Refreshing page show Supporting file incorrectly
If you refresh the page while Supporting files are uploading then they appear to be successfully uploaded even if they are not. This was demonstrated by going through and submitting the Submission and seeing the error  in #1361 

Depends on #1373 #1374

Need to validate based on the status of the `manuscript.files[ ]` and show the correct state (i.e. spinner accordingly)

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

Currently the default client display for an uploaded supporting file is the upload successful state. When refreshing the app while a transaction is still in progress, it doesn't correctly represent the state in which the file data is in the db so files still in the process of being stored in S3 are showing as successful.

This PR adds in the correct initial display of the files state on, refresh however further work will be needed in a separate piece of work to reconnect to a web-socket to track the progress in real time.
 
#### Any relevant tickets

closes #1362

### CODE REVIEW

**Comment by hdrury1** [comment]
Looks good visually- I'm getting an initial error state when first hitting refresh which I presume is the desired outcome.

**Review by hdrury1 — APPROVED** [review]

**Comment by Cooryd** [comment]
> Looks good visually- I'm getting an initial error state when first hitting refresh which I presume is the desired outcome.

I wouldn't expect anything to come back in an error state by default. You might need to reset your db to include the status data which won't exist on old file uploads. The best way to test this is to try to upload a large file > 10MB and then refresh straight away. The app should reload and that file should still appear with a loading spinner instead of the completed arrow icon.

File: app/components/pages/SubmissionWizard/steps/Files/SupportingUpload.js [hunk 1]
```diff
@@ -152,7 +152,9 @@ class SupportingUpload extends React.Component {
       files: props.files.map((file, index) => ({
         file,
         id: index,
-        success: true,
+        success: file.status === 'STORED',
```
Comment (diversemix) [inline app/components/pages/SubmissionWizard/steps/Files/SupportingUpload.js:155]: Cory and I are making a note - that when we eventually write to the ApolloCache we should cosolidate this into a clientStatus (i.e. calculated from the server status)

**Review by diversemix — APPROVED** [review]
