### PR TITLE
Fix semibold issue

### LINKED ISSUE #915: Fonts often too heavy or too light
In various places fonts are either too heavy or too light, depending on browser/device etc.

Usually buttons are too light (at least in chrome on Mac - Mojave renders even lighter but not the only cause)
image

And headings can often be too heavy, especially in Safari and Firefox
image

Have we decided/confirmed how we are intending to achieve the required Noto Sans Semibold? 

https://github.com/elifesciences/elife-xpub/issues/687 doesn't appear to have solved the issue.

It looks like we're using combinations of noto sans, noto sans semibold, and font-weight of 700. In places we have semi bold at 700 which gives extra heavy and blurry headings. And then we aren't using semibold in places we should be. And in some places we use "noto sans" (not semi bold) but use font-weight 700 to "fake" the semi bold weight, but it's blurry.

Where possible we should be using "Noto Sans Semibold" at 400 if this renders correctly. 

Apparently on the journal site it looks like we're achieving semibold by using noto sans and font-weight 700, but apparently where this exists it's actually being switched out with noto sans semibold at 400. I'm not sure how, but gives the results we want. Should we be doing the same in XPub?

I'm happy to investigate when and where it's not displayed correctly, but think we need to decide "how" we're going to apply it properly and then just use it everywhere we want to use semibold.

### PR DESCRIPTION
**Pull request by jsms90**
#### Background
Noto Sans SemiBold + non-Chrome browsers do not play well :cry: 

#### What does this PR do?
- override default font family of `Button` component in pubsweet, to now use `Noto Sans SemiBold`
- over-override font family `Action` component (that sometimes uses Button under the hood), so this is back to just `Noto Sans`
- add `font-weight: 400` everywhere that we use our `fontHeading` theme variable (aka `Noto Sans SemiBold` font family)

#### Any relevant tickets
fixes #915 
relates #687 

#### How has this been tested?
N/A - style change

### CODE REVIEW

**Comment by hdrury1** [comment]
For @chugginselifesciences reference (I'm using Firefox):

screen shot 2018-11-02 at 12 38 05

screen shot 2018-11-02 at 12 37 50

Annoyingly, headers now look good but font weight on buttons looks too heavy.

**Comment by hdrury1** [comment]
Chrome:

screen shot 2018-11-02 at 12 40 07

Safari:

screen shot 2018-11-02 at 12 40 42

File: client/elife-theme/src/elements/ui/Action.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import { css } from 'styled-components'
+import { th } from '@pubsweet/ui-toolkit'
+
+export default css`
+  // Action is sometimes a Link underneath & sometimes a Button
+  // eLife styling makes a button's font: Noto Sans SemiBold
+  // This reverses that override
+  font-family: ${th('fontInterface')};
```
Comment (jsms90) [inline client/elife-theme/src/elements/ui/Action.js]: Hmm, also this overriding the override isn't working. I guess because the Button one is more specific.

So now we have `Action` text (Pre-fill my details) which is more bold than it should be (because it's actually a `Button` with different styling):
image

:thinking:

**Comment by jsms90** [comment]
I guess this needs @chugginselifesciences' input. I've put the label back on the issue, for the purposes of the project board.

File: client/elife-theme/src/elements/ui/Action.js (hunk 1 above)
Comment (jsms90) [reply client/elife-theme/src/elements/ui/Action.js]: Fixed in the latest commit

**Comment by chugginselifesciences** [comment]
> I guess this needs @chugginselifesciences' input. I've put the label back on the issue, for the purposes of the project board.

Hi @jsms90. I've followed Hem's instructions to take a look on the style guide, but it's not loading fonts correctly (it's showing Arial). If @hdrury1 is ok with it can I suggest you get to a point where you think it looks close to what we're aiming for, and then merge and put it in the design review column and then I can take a look on staging?

The screenshots look ok to me.

@diversemix does this make sense to you given your investigations into the problem I'm having?

**Comment by jsms90** [comment]
@chugginselifesciences Yeah that's fair enough. I was forgetting that you wouldn't be able to see these components correctly yet.

So essentially, this is what we have atm:

1. Chrome
image
image


2. Firefox
image
image

Same code. Different browsers :cry:

**Comment by diversemix** [comment]
@jsms90 ... what we are finding is that what the browser says is displayed in the `Element` tab is certainly not what is displayed. @Cooryd and I did some playing around with code and within the browser and we cannot force the styleguide to be show what is shown within the app. 

For visuals appearances like fonts the styleguide is currently useless. FYI: @hdrury1

**Comment by jsms90** [comment]
Yeah I completely understand @diversemix. But what we're discussing now is a separate issue - #913. One that is affecting Chris' ability to review this PR before we merge.

I completely agree that #913 needs sorting out, if we're going to enable Chris to review components using styleguidist. We definitely need to do that, otherwise @chugginselifesciences needs to wait until we've finished developing an entire epic at times, before being able to offer a design review, which obviously slows down our cycles.

But in the meantime, while styleguidist is not representative, I'm hoping that the copy/pasted pictures above while do for now?

File: client/elife-theme/src/elements/ui/Action.js (hunk 1 above)
Comment (chugginselifesciences) [reply client/elife-theme/src/elements/ui/Action.js]: I think we need option 3. I might now know enough about the implications for pubsweet, but my understanding is if we need something, we do it, and if it's helpful to pubsweet we add it.

I don't think pubsweet should prevent us doing what we need to do in this instance, and it seems like it might helpful to others to have the option to have different fonts/weights on "buttons" and "links". So unless there's a problem or reason I'm not aware of I think we should we should go with:

> adding a prop to pubsweet's Action component, to provide us with some way of differentiating between Actions which are actually Links & Actions which are actually Buttons

One thing that might be worth noting is that we have `Link`s that use both Noto Sans and Noto Serif fonts - not sure if its related but surely using different `font-family`s
