### PR TITLE
2104 - fix null last step

### LINKED ISSUE #2104: browser tests failing on /null
## Subtasks

- [ ] A description of a subtask
- [ ] A description

## Assumptions and notes
- We could use this technology
- More notes or suggestions

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

Gives a new submission an initial `lastStepVisited`  value of `/submit/${id}/author` when it is created to prevent the `null` link if the user navigates away before auto save. Also adds protections into the `DashboardListItem` to link to author step if `lastStepVisited` is `null`.

#### Any relevant tickets

closes #2104

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [x] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

#### UI Changes

- [ ] Has been reviewed against Designs
- [ ] Necessary updates to styleguide

### CODE REVIEW

File: packages/component-dashboard/server/resolvers.js [hunk 1]
```diff
@@ -18,6 +18,8 @@ const resolvers = {
       const userUuid = await models.User.getUuidForProfile(user)
       const manuscript = models.Manuscript.makeInitial({ createdBy: userUuid })
       manuscript.setDefaults()
+      await manuscript.save()
```
Comment (Cooryd) [inline packages/component-dashboard/server/resolvers.js:21]: This save needs to happen first as the id is generated on the `$beforeInsert`. We need the id before we can generate the url string

Comment (diversemix) [inline packages/component-dashboard/server/resolvers.js:21]: why the two saves?

**Review by diversemix — APPROVED** [review]

File: packages/component-dashboard/server/resolvers.js (hunk 1 above)
Comment (diversemix) [reply packages/component-dashboard/server/resolvers.js:21]: Seems pedantic - but can we add this as a comment? Would be easy for someone to revisit this later and "remove the double-save".

Comment (Cooryd) [reply packages/component-dashboard/server/resolvers.js:21]: > This save needs to happen first as the id is generated on the `$beforeInsert`. We need the id before we can generate the url string

Comment (Cooryd) [reply packages/component-dashboard/server/resolvers.js:21]: Yes, otherwise we can use uuid to create `id` here and pass to factory?

**Review by petereast — APPROVED** [review]
Assuming you put in the [comment](https://github.com/elifesciences/elife-xpub/pull/2106/files#diff-78bce7d52359287c17e265ff3ece5a86R21), it seems ok for me

**Review by diversemix — APPROVED** [review]
