### PR TITLE
1528 - ScienceBeam feedback

### LINKED ISSUE #1528: Implementing ScienceBeam Feedback loop
Whenever there is a change to the manuscript title log the change out (along with the manuscript id).
This will allow the logs to be parsed to generate a set of incorrectly extracted titles to train sciencebeam with.

I think this is the bear minimum - we could also store the extracted title in the database - that way we can maintain the history. 

/cc @de-code

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

Adds a SemanticExtraction model to the app. An instance of this extraction is created and saved when ScienceBeam extracts a manuscripts title. This information will then be used in conjunction with the `Manuscript` title once it has been fully submitted to provide feedback to guide improvments.

#### Any relevant tickets

closes #1528 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

- [x] Unit / Integration tests

### CODE REVIEW

File: server/xpub-model/migrations/1551872573-semantic-extraction.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+CREATE TABLE semantic_extraction (
+    id UUID PRIMARY KEY,
+    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
+    updated TIMESTAMP WITH TIME ZONE,
+    manuscript_id UUID NOT NULL,
+    field_name TEXT NOT NULL,
+    value TEXT NOT NULL
```
Comment (Cooryd) [inline server/xpub-model/migrations/1551872573-semantic-extraction.sql]: this probably should be nullable

File: server/xpub-model/entities/semanticExtraction/index.js [hunk 2]
```diff
@@ -0,0 +1,24 @@
+const BaseModel = require('@pubsweet/base-model')
+
+class AuditLog extends BaseModel {
```
Comment (diversemix) [inline server/xpub-model/entities/semanticExtraction/index.js]: Incorrect name?

File: server/xpub-controller/helpers/files.js [hunk 3]
```diff
@@ -127,6 +126,14 @@ class FilesHelper {
         filename,
       })
     }
+
+    const semanticExtractionEntity = new SemanticExtractionModel({
```
Comment (diversemix) [inline server/xpub-controller/helpers/files.js]: I'd suggest creating factory methods for all the different field types. That way we don't expose field as a string - rather its a method like `SemanticExtractionModel.createTitleEntry(manuscriptId, title)`

**Review by diversemix — APPROVED** [review]

**Review by hem-brahmbhatt — APPROVED** [review]
