### PR TITLE
fixed issue with modal overlay not scrolling

### LINKED ISSUE #1980: Users cannot scroll list of editors on Windows 7, Firefox 66
**Describe the bug**
* Login to the application
* Start a new submission and fill in details
* In the editors step you cannot scroll using the scroll bar, only with mouse or trackpad or up and down arrows

**Expected behavior**
It should scroll down the list of editors

**Screenshots**
elife-scroll-bug-firefox

**Device, Operating System and Browser**
Windows 7, Firefox 66

### PR DESCRIPTION
**Pull request by erezmus**
#### Background

Fixes Issue with modal overlay not scrolling with scrollbar on certain browsers.

#### Any relevant tickets

closes #1980

### CODE REVIEW

File: packages/component-elife-ui/client/molecules/ModalOverlay.js [hunk 1]
```diff
@@ -52,6 +52,18 @@ class ModalOverlay extends React.Component {
     this.overlay = React.createRef()
   }
 
+  componentDidUpdate(prevProps, prevState, snapshot) {
```
Comment (Cooryd) [inline packages/component-elife-ui/client/molecules/ModalOverlay.js:55]: Is this also in the Pubsweet modal component? If not, might be worth putting in a MR / raising an issue there too so this doesn't reappear when we upgrade and start using the shared component

Comment (Cooryd) [inline packages/component-elife-ui/client/molecules/ModalOverlay.js]: Is this also in the Pubsweet modal component? If not, might be worth putting in a MR / raising an issue there too so this doesn't reappear when we upgrade and start using the shared component

**Review by Cooryd — APPROVED** [review]

**Review by petereast — APPROVED** [review]
