### PR TITLE
resume navigation to the last visited page

### LINKED ISSUE #1063: Navigation to the last visited page is broken
latest changes have removed navigation to the last visited page on continue submission

### PR DESCRIPTION
**Pull request by jyenes**
#### Background

What does this PR do?
closes #1063 

#### How has this been tested?
there's another ticket to create a proper browser test for that #1088

see #1088

#### UI Changes

- [x] Has been reviewed against Designs
- [x] Necessary updates to styleguide

### CODE REVIEW

**Review by SemraSh — APPROVED** [review]
LGTM 👍

File: app/components/pages/Dashboard/operations.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ export const ALL_MANUSCRIPTS = gql`
         title
       }
       clientStatus
+      formState
```
Comment (SemraSh) [inline app/components/pages/Dashboard/operations.js]: Maybe we can change the name to be something more explanatory, like `previousPage`, `lastVisitedPage` if that makes sense?

Comment (diversemix) [reply app/components/pages/Dashboard/operations.js]: `lastVisitedPage` :+1:

Comment (damnhipster) [reply app/components/pages/Dashboard/operations.js]: This would require a migration, which should be automatically applied, but we haven't actually run a migration since we created Production and Staging last month so there may be some manual steps needed.

And in the spirit of getting small tickets/issues through, I suggest moving this change to a separate PR/issue.

Comment (jyenes) [reply app/components/pages/Dashboard/operations.js]: agree on move this to a separate ticket

Comment (jyenes) [reply app/components/pages/Dashboard/operations.js]: so new ticket raised #1097 for refactor the field name
