### PR TITLE
2189 - Scroll to top of form on navigating next or back

### LINKED ISSUE #2189: Application doesn't scroll to top of page on new step
**Describe the bug**
Navigating to the next step in the wizard doesn't place the user at the top of the page

**Steps To Reproduce**
Resize viewport to increase scroll behaviour
Begin new submission
Fill in, e.g. files page and scroll to bottom to click 'Next'
Observe the page loads with the viewport in the same place

**Expected behavior**
Page should scroll to top of the window so user can complete the step from top to bottom

### PR DESCRIPTION
**Pull request by Cooryd**
#### Background

When navigating through the wizard steps the user should be taken to the top of the current step when using the 'Next' or 'Back' buttons. 

#### Any relevant tickets

closes #2189

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [x] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

#### UI Changes

- [ ] Has been reviewed against Designs
- [ ] Necessary updates to styleguide

### CODE REVIEW

File: packages/component-submission/client/pages/SubmissionWizard.js [hunk 1]
```diff
@@ -230,12 +234,7 @@ export const SubmissionWizard = ({
                         onClick={() => {
                           formikProps.validateForm().then(errors => {
                             if (!Object.keys(errors).length) {
-                              setCurrentStep(currentStep + 1)
-                              history.push(
-                                `${match.url}/${STEP_NAMES[
-                                  currentStep + 1
-                                ].toLowerCase()}`,
-                              )
+                              navigateToStep(currentStep + 1)
```
Comment (diversemix) [inline packages/component-submission/client/pages/SubmissionWizard.js:237]: loving the refactord fn! :heart:

**Review by diversemix — APPROVED** [review]

File: packages/component-submission/client/pages/SubmissionWizard.test.js [hunk 2]
```diff
@@ -143,6 +144,34 @@ describe('SubmissionWizard', async () => {
...
+      await flushPromises()
+
+      expect(scrollSpy).toBeCalledTimes(1)
+      expect(scrollSpy).toBeCalledWith(0, 0)
+    })
+
+    it('scrolls to top on back', async () => {
+      const { getByTestId } = renderWithPath('/submit/id/files', pushHistory)
+
+      expect(scrollSpy).toBeCalledTimes(0)
```
Comment (Cooryd) [inline packages/component-submission/client/pages/SubmissionWizard.test.js:162]: Assumption made here that we'll always be using `scrollTo` to scroll the user to the top of the window. Was a bit unhappy doing this as it's asserting implementation detail. However couldn't find a simple way of generically checking the scroll of window global. Let me know if you can think of anything. This does the job of adding coverage for now.

**Review by petereast — APPROVED** [review]

**Review by will-byrne — APPROVED** [review]
