### PR TITLE
Disable autosave when uploading

### LINKED ISSUE #2051: Disable AutoSave on file upload
## Subtasks
- [ ] disable the autosave during file upload to prevent the data inconsistency issues.

## Assumptions and notes
- If this fails we will perform a raw db update on just the cover letter to bypass the integrity check.

### PR DESCRIPTION
**Pull request by will-byrne**
#### Background

Disable autosave while files are uploading

- [x] Auto save and save on next disabled on upload
- [x] Trigger save if form changes made during upload then upload completes
- [x] `fileStatus` validation working on going back then next while upload is in progress
- [x] Auto save disabled when submitting
- [ ] Ensure `lastStepVisited` is set to the author step when first creating the manuscript
#### Any relevant tickets

Closes #2051

### CODE REVIEW

**Review by petereast — APPROVED** [review]
Sure

**Review by Cooryd — APPROVED** [review]

**Review by diversemix — APPROVED** [review]

**Comment by Cooryd** [comment]
We've got autosave and save on next disabled during uplaod now. This has introduced a bug with validation of `fileStatus` when going back then next when something is uploading that needs addressing

**Comment by Cooryd** [comment]
If this issue causes too many issues, we may need to disable 'back' as well as 'next' navigation while files upload.

File: packages/component-submission/client/components/WizardStep.js [hunk 1]
```diff
@@ -48,7 +47,8 @@ class WizardStep extends React.Component {
         // ensure each page gets a new form instance otherwise all fields are touched
         key={title}
         onSubmit={values => {
-          handleButtonClick(values).then(() => history.push(nextUrl))
+          handleButtonClick({ ...values, lastStepVisited: nextUrl })
```
Comment (Cooryd) [inline packages/component-submission/client/components/WizardStep.js]: This was my own change but will moving the `history.push` out of the resolved promise cause any issues when the form does need to save when navigating? will we lose the last 5 seconds of data?

**Comment by petereast** [comment]
Okay, so now there's autosave weirdness - I had problems with changes I made being reset on the <kbd>Author</kbd> and <kbd>Details</kbd> pages.

Thank you, _browser tests_ - that could've been nasty :1st_place_medal:

File: packages/component-submission/client/pages/FilesStepPage.js [hunk 2]
```diff
@@ -76,8 +74,7 @@ export class FilesStepPageComponent extends React.Component {
           manuscriptUploadingError: error,
         })
       })
-      .finally(() => {
-        disableSave(false)
+      .then(() => {
```
Comment (Cooryd) [inline packages/component-submission/client/pages/FilesStepPage.js]: We'll be stuck in a state of `isUploading` if this throws an error. This will then cause the client to be stuck in the converting stater so the error will be hidden
