### PR TITLE
1496 send email when MECA import fails

### LINKED ISSUE #1496: xpub-tech-alerts not working in production
We've had an EJP failure in production and no email was sent ...

```
a9fc13af-4c94-44a0-ae51-34ab58b666d5 | 2019-02-09 03:45:41.863+00 | MECA_IMPORT_FAILED
```

### PR DESCRIPTION
**Pull request by hem-brahmbhatt**
#### Background

Sends an email when EJP request the callback route to let us know that importing failed.

#### Any relevant tickets

Closes #1496 

#### How has this been tested?
**Reviewers** ensure that these test requirements are also reviewed.

Please indicate the need for this change to be tested. If not please justify, if so then at what levels. 

- [x] Unit / Integration tests
- [ ] Browser tests
- [ ] End2end tests

### CODE REVIEW

File: server/jest-setup.js [hunk 1]
```diff
@@ -4,12 +4,14 @@ const replaySetup = require('../test/helpers/replay-setup')
 replaySetup('success')
 
 jest.mock('@pubsweet/component-send-email', () => ({
+  _sendPromise: null,
   mails: [],
   send(mailData) {
-    return new Promise((resolve, reject) => {
+    this._sendPromise = new Promise((resolve, reject) => {
```
Comment (hem-brahmbhatt) [inline server/jest-setup.js:10]: This allows us to await the Promise so we don't have to [wait with a loop](https://github.com/elifesciences/elife-xpub/blob/1496-send-email/server/xpub-server/entities/manuscript/resolvers/submitManuscript.test.js). This will be refactored to use the new way in a separate PR.

**Comment by Cooryd** [comment]
Failed tests, looks like we're either not clearning down the `mail` before the test or two emails are being sent.

```
      91 |       .expect(204)

      92 |     await mailer._sendPromise

    > 93 |     expect(mailer.getMails()).toHaveLength(1)

         |                               ^

      94 |     expect(mailer.getMails()[0]).toMatchObject({

      95 |       text: expect.stringContaining(manuscript.id)

      96 |     })

```

**Review by diversemix — APPROVED** [review]

**Review by Cooryd — APPROVED** [review]
